import {
  BAKEABLE_VERDICTS,
  type SourceRecord,
} from "./source-verify.js";

export const SOURCE_REGISTRY = [
  {
    id: "abs-sa2-income-dbr",
    name: "ABS Data by Region — median equivalised household income (weekly)",
    url: "https://dbr.abs.gov.au/",
    licence: "CC BY 4.0",
    period: "2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-rent-2021",
    name: "ABS Census 2021 — median weekly household rental payment (SA2)",
    url: "https://www.abs.gov.au/databyregion",
    licence: "CC BY 4.0",
    period: "2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-rent-to-income-2021",
    name: "Rent-to-income ratio — ABS Census 2021 median weekly rent ÷ ABS Data by Region equivalised household income",
    url: "https://dbr.abs.gov.au/",
    licence: "CC BY 4.0",
    period: "2021",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-erp-sa2",
    name: "ABS ERP by SA2",
    url: "https://www.abs.gov.au/statistics/people/population/regional-population",
    licence: "CC BY 4.0",
    period: "2023",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-erp-sa2-series",
    name: "ABS ERP by SA2 — full annual series (2001–2023)",
    url: "https://www.abs.gov.au/statistics/people/population/regional-population",
    licence: "CC BY 4.0",
    period: "2001–2023",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-tsp-sa2",
    name: "ABS Census 2021 Time Series Profile (C21_T02_SA2) - median income/mortgage/rent by SA2 (2011/2016/2021)",
    url: "https://www.abs.gov.au/census/find-census-data",
    licence: "CC BY 4.0",
    period: "2011-2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vcsa-recorded-offences",
    name: "VCSA Recorded offences — suburb (Table 03) + LGA fallback (Table 02)",
    url: "https://www.crimestatistics.vic.gov.au/crime-statistics/latest-victorian-crime-data/download-data",
    licence: "CC BY 3.0 AU",
    verifyNote: "Download-data tables carry CC BY 3.0 AU; some CSA web pages state CC BY 4.0 - re-verify at next refresh (checked 2026-06-10)",
    period: "2025 (latest year in export)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "act-policing-crime-statistics",
    name: "ACT Policing — quarterly crime statistics by suburb (dataACT)",
    url: "https://www.data.act.gov.au/Justice-Safety-and-Emergency/ACT-Crime-Statistics/2egm-dieb",
    licence: "CC BY 4.0",
    period: "rolling year (latest 4 quarters in export)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "qps-lga-offence-rates",
    name: "QPS - LGA reported offence rates per 100k ERP (data.qld.gov.au)",
    url: "https://www.data.qld.gov.au/dataset/lga_reported_offences_rates",
    licence: "CC BY 4.0",
    period: "rolling year (latest 12 months in export)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "bocsar-suburb-offences",
    name: "BOCSAR - recorded criminal incidents by NSW suburb by month (data.nsw)",
    url: "https://data.nsw.gov.au/data/dataset/crime-by-offence-by-nsw-suburb",
    licence: "CC BY 4.0",
    period: "rolling year (latest 12 months in export)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "wa-police-suburb-offences",
    name: "WA Police Force - recorded offences by locality by month (crime statistics portal Power BI report)",
    url: "https://www.wa.gov.au/organisation/western-australia-police-force/crime-statistics",
    licence: "WA Government Terms of Use (attribution required)",
    verifyNote: "Portal page carries the generic wa.gov.au Terms of Use, which permit attributed personal/non-commercial/in-organisation reuse but require WRITTEN PERMISSION for commercial use - the data.wa.gov.au WA Police org otherwise publishes CC BY 4.0. CONFIRM commercial-reuse permission (email WA Police, or locate a CC BY catalogue entry for the suburb crime series) before commercial launch (checked 2026-06-12).",
    period: "rolling year (latest 12 months in export)",
    licenceVerdict: "non-commercial-or-restricted",
  },
  {
    id: "sapol-suburb-offences",
    name: "SAPOL - crime statistics by suburb by reported date (data.sa.gov.au)",
    url: "https://data.sa.gov.au/data/dataset/crime-statistics",
    licence: "CC BY",
    verifyNote: "Suburb-level violent counts EXCLUDE sexual offences: SAPOL withholds the incident suburb for every sexual-offence row (published as NOT DISCLOSED), so they can never join to a place. Methodology footnote, not a blocker (checked 2026-06-12).",
    period: "rolling year (latest 12 months across the two newest fiscal-year CSVs)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "qld-spp-bushfire-prone-area",
    name: "QFES Bushfire Prone Area - Queensland series (SPP natural hazards mapping)",
    url: "https://qldspatial.information.qld.gov.au/catalogue/catalog/search/resource/details.page?uuid=%7B8712BDE4-27D1-49A2-83F1-AE7A692B816D%7D",
    method: "QSpatial ClipZipShip prepackaged regional download (DP_SouthEastQueensland_BPA.zip, GDA94 Australia Albers shapefile), clipped to the region bbox locally - replaces paged queries against the AGOL utility proxy, which 504'd unrecoverably; same July 2017 data vintage either way",
    licence: "CC BY 4.0",
    period: "July 2017 series",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "bcc-cityplan-flood-overlay",
    name: "Brisbane City Plan 2014 - Flood overlay (river, creek/waterway and overland flow flood planning areas; Brisbane LGA only)",
    url: "https://data.brisbane.qld.gov.au/explore/dataset/cp14-flood-overlay-brisbane-river-flood-planning-area/",
    licence: "CC BY 4.0",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "nsw-rfs-bush-fire-prone-land",
    name: "NSW Bush Fire Prone Land - RFS mapped categories (NSW Spatial Services hosted layer)",
    url: "https://portal.spatial.nsw.gov.au/server/rest/services/Hosted/NSW_BushFire_Prone_Land/FeatureServer/0",
    licence: "CC BY 4.0",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "nsw-epi-flood-planning-area",
    name: "NSW Flood Planning Area - EPI hazard layer (NSW Planning Portal / DPE ePlanning)",
    url: "https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/ePlanning/Planning_Portal_Hazard/MapServer/230",
    licence: "CC BY 4.0",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "wa-dfes-bushfire-prone-areas-2025",
    name: "WA Bush Fire Prone Areas 2025 - DFES designation (Landgate SLIP public services)",
    url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Bush_Fire_Prone_Areas/MapServer/22",
    licence: "CC BY 4.0",
    verifyNote: "DFES bushfire-prone-areas published open on data.wa.gov.au / SLIP public services (CC BY 4.0). WA DWER 1% AEP floodway/fringe is INTENTIONALLY NOT shipped - it is CC BY-NC (non-commercial) and Festra serves data as public tiles, so Perth is bushfire-only (checked 2026-06-13).",
    period: "2025 designation",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "sa-plansa-bushfire-hazards",
    name: "PlanSA Bushfire hazard overlays - Property Planning Atlas (SA DIT)",
    url: "https://lsa2.geohub.sa.gov.au/arcgis/rest/services/SAPPA/PropertyPlanningAtlasV18/MapServer",
    licence: "CC BY 4.0",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "sa-plansa-flood-hazards",
    name: "PlanSA Flood hazard overlays - Property Planning Atlas (SA DIT)",
    url: "https://lsa2.geohub.sa.gov.au/arcgis/rest/services/SAPPA/PropertyPlanningAtlasV18/MapServer",
    licence: "CC BY 4.0",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "nsw-beachwatch",
    name: "NSW Beachwatch - beach water quality (enterococci grades; DPE)",
    url: "https://www.beachwatch.nsw.gov.au/",
    licence: "CC BY 4.0",
    period: "rolling (latest samples)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "ptv-gtfs",
    name: "PTV GTFS Schedule — metropolitan train, tram, bus (DTP)",
    url: "https://opendata.transport.vic.gov.au/dataset/gtfs-schedule",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "tfnsw-gtfs",
    name: "Transport for NSW - complete GTFS schedule",
    url: "https://opendata.transport.nsw.gov.au/data/dataset/timetables-complete-gtfs",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["sydney"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "translink-gtfs",
    name: "Translink - South East Queensland GTFS schedule",
    url: "https://www.data.qld.gov.au/dataset/general-transit-feed-specification-gtfs-translink",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["brisbane"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "adelaide-metro-gtfs",
    name: "Adelaide Metro GTFS schedule",
    url: "https://data.sa.gov.au/data/dataset/https-gtfs-adelaidemetro-com-au",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["adelaide"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "transperth-gtfs",
    name: "Transperth (PTA WA) GTFS schedule",
    url: "https://www.transperth.wa.gov.au/About/Spatial-Data-Access",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["perth"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "tas-gtfs",
    name: "Tasmania statewide GTFS schedule (Metro Tasmania + regional operators)",
    url: "https://www.transport.tas.gov.au/public_transport/gtfs-data",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["hobart"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "nt-gtfs",
    name: "NT Government GTFS schedule - Darwin bus network",
    url: "https://data.nt.gov.au/dataset/bus-timetable-data-and-geographic-information-darwin",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["darwin"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "transport-canberra-gtfs",
    name: "Transport Canberra GTFS schedule (bus + light rail)",
    url: "https://www.transport.act.gov.au/contact-us/information-for-developers",
    licence: "CC BY 4.0",
    period: "rolling schedule export",
    regions: ["canberra"],
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-pt",
    name: "OpenStreetMap — public transport stops (Overpass fallback only)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-mapshare-hospitals",
    name: "Vicmap / MapShare — general hospitals (Emergency Services FOI)",
    url: "https://enterprise.mapshare.vic.gov.au/server/rest/services/Hosted/Emergency_Services__VMFEAT_FOI_POINT_/FeatureServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-health",
    name: "OpenStreetMap — GP/clinic points (Overpass; hospital fallback only)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "doh-mmm-2023",
    name: "Modified Monash Model 2023 - health-access remoteness (MM1-7) by SA1, rolled up to SA2 (Dept of Health and Aged Care)",
    url: "https://data.gov.au/data/dataset/modified-monash-model-mmm-2023",
    licence: "CC BY 4.0",
    verifyNote: "The data.gov.au catalogue record states CC BY 4.0; some Dept of Health/ArcGIS metadata and legacy downloads refer to Creative Commons Attribution 2.5 Australia. Both are attribution-compatible and bakeable, but re-check on refresh (checked 2026-06-13).",
    period: "2023 (published Mar 2025)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-post",
    name: "OpenStreetMap — post offices / LPO points (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-clinical-social",
    name: "OpenStreetMap — pathology labs + NDIS/disability-related providers (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-labour-2016",
    name: "ABS Census 2016 — labour force (employed, participation) by SA2",
    url: "https://dbr.abs.gov.au/",
    licence: "CC BY 4.0",
    period: "2016",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-planning-bpa",
    name: "Vicmap Planning — Bushfire Prone Area (regulatory overlay)",
    url: "https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/ArcGIS/rest/services/Vicmap_Planning/FeatureServer/9",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-planning-flood",
    name: "Vicplan — Land Subject to Inundation overlay (LSIO; SBO unavailable from API)",
    url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeOverlays/MapServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-schools",
    name: "OpenStreetMap — schools within 2 km (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-preschool-2021",
    name: "ABS Census 2021 — children enrolled in preschool (SA2)",
    url: "https://dbr.abs.gov.au/",
    licence: "CC BY 4.0",
    period: "2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-seifa-2021",
    name: "ABS SEIFA 2021 — IRSAD and IRSD deciles + percentiles (SA2)",
    url: "https://www.abs.gov.au/statistics/people/people-and-communities/socio-economic-indexes-areas-seifa-australia/latest-release",
    licence: "CC BY 4.0",
    period: "2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-community-2021",
    name: "ABS Census 2021 — tenure and dwelling structure (SA2)",
    url: "https://dbr.abs.gov.au/",
    licence: "CC BY 4.0",
    period: "2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-g49-sa2",
    name: "ABS Census 2021 non-school qualification level (C21_G49_SA2) - bachelor+ and postgraduate share by SA2",
    url: "https://www.abs.gov.au/census/find-census-data",
    licence: "CC BY 4.0",
    period: "2021",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-amenities",
    name: "OpenStreetMap — everyday amenities for 15-min access (supermarket, pharmacy, park, cafe/restaurant, gym/leisure; Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-cycleways",
    name: "OpenStreetMap — cycling infrastructure for cyclability index (cycleways, on-road bike lanes, bicycle-designated paths; Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL — attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-aged-care",
    name: "OpenStreetMap - aged care / retirement facilities (nursing home, assisted living; Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL - attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vicmap-police",
    name: "Vicmap / MapShare — police stations (Emergency Services FOI)",
    url: "https://enterprise.mapshare.vic.gov.au/server/rest/services/Hosted/Emergency_Services__VMFEAT_FOI_POINT_/FeatureServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vicmap-foi",
    name: "Vicmap Features of Interest — child-care centres (DTP Victoria)",
    url: "https://services-ap1.arcgis.com/P744lA0wf4LlBZ84/ArcGIS/rest/services/Vicmap_Features_of_Interest/FeatureServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-planning-heritage",
    name: "Vicplan — Heritage Overlay (HO) area share per SA2 (DTP Victoria)",
    url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeOverlays/MapServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-planning-overlays",
    name: "Vicplan - conservation & restriction overlays (ESO/SLO/VPO/EMO/EAO/PAO) area share per SA2 (DTP Victoria)",
    url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Vicplan_PlanningSchemeOverlays/MapServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-coastal-inundation",
    name: "DEECA Future Coasts - coastal inundation (sea-level rise) scenario share per SA2, via CoastKit",
    url: "https://biod-gis.mapshare.vic.gov.au/arcgis/rest/services/CoastKit/LCHAInundation/MapServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "2040-2100 projection",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-fire-history",
    name: "Vicmap / DEECA Fire History - Last Burnt (burnt-area share per SA2)",
    url: "https://discover.data.vic.gov.au/dataset/fire-history-overlay-of-most-recent-fires",
    licence: "CC BY 4.0 (Victoria)",
    period: "to 2022-23",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vif2023-sa2",
    name: "Victoria in Future 2023 - SA2 population + dwelling projections to 2036 (DTP)",
    url: "https://www.data.vic.gov.au/victoria-future-2023-vif2023-data-available-excel-spreadsheets",
    licence: "CC BY 4.0 (Victoria)",
    period: "2021-2036 projection",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-building-approvals",
    name: "ABS Building Approvals by SA2 (BA_SA2) - dwelling units approved, monthly",
    url: "https://www.abs.gov.au/statistics/industry/building-and-construction/building-approvals-australia",
    licence: "CC BY 4.0",
    period: "monthly (rolling)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-school-zones",
    name: "Victorian Government School Zones (Dept of Education) - primary + secondary (Year 7) zones",
    url: "https://discover.data.vic.gov.au/dataset/victorian-government-school-zones-2026",
    licence: "CC BY 4.0",
    period: "2026 school year",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "dtp-aadt",
    name: "DTP Annual Average Daily Traffic Volume (arterials + highways, vehicles/day)",
    url: "https://discover.data.vic.gov.au/dataset/historical-annual-average-daily-traffic-volume",
    licence: "CC BY 4.0",
    period: "2019 (latest published)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-water-corp",
    name: "Vicmap water corporation boundaries - metro retailers (Yarra Valley / South East / Greater Western Water)",
    url: "https://discover.data.vic.gov.au/dataset/melbourne-water-retailers",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-parcel",
    name: "Vicmap parcel boundaries - lot size at a point (runtime WFS query, area geometry-derived)",
    url: "https://www.land.vic.gov.au/maps-and-spatial/spatial-data/vicmap-catalogue",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vicplan-live",
    name: "VicPlan / Vicmap Planning - planning zone + overlays at a point (runtime WFS query, live endpoint)",
    url: "https://opendata.maps.vic.gov.au/geoserver/wfs",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "epa-air",
    name: "EPA Victoria Air Monitoring (AirWatch) - nearest fixed site + latest health-advice band",
    url: "https://www.epa.vic.gov.au/for-community/airwatch",
    licence: "CC BY 4.0",
    period: "hourly (snapshot captured at build)",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-activity-centres",
    name: "Vicmap Planning - Activity Centre Zones (ACZ) directing higher-density development",
    url: "https://discover.data.vic.gov.au/dataset/vicmap-planning",
    licence: "CC BY 4.0 (Victoria)",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-noise-corridors",
    name: "OpenStreetMap - rail / tram / freeway corridors for the transport-noise proximity proxy (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL - attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-nuisance-points",
    name: "OpenStreetMap - industrial / waste / sewage / quarry points for the nuisance proximity proxy (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL - attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-train-stations",
    name: "OpenStreetMap - train stations for nearest-station distance (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL - attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "osm-future-transport",
    name: "OpenStreetMap - under-construction / proposed PT stations (Overpass)",
    url: "https://www.openstreetmap.org/",
    licence: "ODbL - attribute OSM",
    period: "current",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-doe-school-locations",
    name: "Victorian Dept of Education - School Locations (sector + coordinates)",
    url: "https://discover.data.vic.gov.au/dataset/school-locations-2025",
    licence: "CC BY 4.0",
    period: "2025",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-cooling-greening",
    name: "Cooling and Greening Melbourne - Urban Heat 2018 (land-surface-temperature uplift, UHI18_M) - runtime ArcGIS pin lookup",
    url: "https://discover.data.vic.gov.au/dataset/metropolitan-melbourne-urban-heat-islands-and-urban-vegetation-2018",
    licence: "CC BY 4.0 (Victoria)",
    period: "2018",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "abs-census-volunteering-2021",
    name: "ABS Census 2021 G23 - voluntary work, % of residents (SA2), via Digital Atlas of Australia",
    url: "https://www.abs.gov.au/census/find-census-data",
    licence: "CC BY 4.0",
    period: "2021",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-tree-canopy",
    name: "Vegetation Cover for Metropolitan Melbourne 2018 - tree canopy % (PERANYTREE) - runtime ArcGIS pin lookup",
    url: "https://discover.data.vic.gov.au/dataset/vegetation-cover-for-metropolitan-melbourne-2018",
    licence: "CC BY 4.0 (Victoria)",
    period: "2018",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-anef",
    name: "ANEF aircraft-noise contours - Melbourne Airport 2022 Master Plan + Avalon (Vicmap/VicPlan) - runtime pin lookup",
    url: "https://plan-gis.mapshare.vic.gov.au/arcgis/rest/services/Planning/Melbourne_Airport_Master_Plan_2022_VicPlan/MapServer",
    licence: "CC BY 4.0 (Victoria)",
    period: "2022",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "aec-federal-2022",
    name: "AEC 2022 federal election - members elected + two-party-preferred by division (results CSVs; electorate lens retired 2026-06-09)",
    url: "https://results.aec.gov.au/27966/Website/HouseDownloadsMenu-27966-Csv.htm",
    licence: "CC BY 4.0 (AEC)",
    verifyNote: "The former AEC Federal Electoral Boundaries 2025 'pin lookup' was stale and is removed; if the electorate lens returns, use Geoscape Administrative Boundaries (CC BY 4.0) for division geometry. Results CSVs stay CC BY 4.0.",
    period: "2022",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vic-state-districts",
    name: "Victorian state Legislative Assembly districts (Vicmap Admin STATE_ASSEMBLY_2022) - runtime pin lookup",
    url: "https://discover.data.vic.gov.au/dataset/vicmap-admin",
    licence: "CC BY 4.0 (Victoria)",
    period: "2022",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "epa-beach-report",
    name: "EPA Victoria Beach Report - enterococci sampling (bay beach swim quality), graded on median of recent samples",
    url: "https://discover.data.vic.gov.au/dataset/beach-report-enterococci-data",
    licence: "CC BY 4.0",
    period: "to 2025",
    derived: true,
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "bom-solar-climatology",
    name: "Bureau of Meteorology - average daily solar exposure (Melbourne climatology); regional figure for the rooftop-solar lens",
    url: "http://www.bom.gov.au/climate/data/index.shtml",
    licence: "BoM copyright - verify before commercial use",
    verifyNote: "Could not verify a CC BY notice on the CDO product page (checked 2026-06-10). BoM's copyright page defaults to personal/within-organisation use unless a page states a CC licence; third-party docs (weatherOz) report CC BY 3.0 AU for CDO station data. Confirm with BoM before commercial use.",
    period: "long-term mean",
    derived: true,
    licenceVerdict: "non-commercial-or-restricted",
  },
  {
    id: "vgv-median-house-suburb",
    name: "Valuer-General Victoria - Property Sales Report, median house price by suburb (annual time series)",
    url: "https://discover.data.vic.gov.au/dataset/victorian-property-sales-report-median-house-by-suburb-time-series",
    licence: "CC BY 4.0",
    period: "2014-2023",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "vgv-median-unit-suburb",
    name: "Valuer-General Victoria - Property Sales Report, median unit price by suburb (annual time series)",
    url: "https://discover.data.vic.gov.au/dataset/victorian-property-sales-report-median-unit-by-suburb-time-series",
    licence: "CC BY 4.0",
    period: "2015-2024",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "dffh-rental-report-suburb",
    name: "Homes Victoria / DFFH - Rental Report, moving annual median rent by suburb (quarterly)",
    url: "https://discover.data.vic.gov.au/dataset/rental-report-quarterly-moving-annual-rents-by-suburb",
    licence: "CC BY 4.0",
    period: "year to Sep 2025",
    licenceVerdict: "open-with-attribution",
  },
  {
    id: "wa-dwer-fpm-100aep-floodway-fringe",
    name: "WA DWER FPM 1 in 100 (1%) AEP Floodway and Flood Fringe Area (DWER-014)",
    url: "https://public-services.slip.wa.gov.au/public/rest/services/SLIP_Public_Services/Water/MapServer/23",
    licence: "CC BY-NC (DataWA Custom / ArcGIS layer description)",
    verifyNote: "SLIP public Water MapServer layer 23; DataWA access is Open but licence is Custom (Active Acceptance), and the ArcGIS layer description says Creative Commons Non-Commercial. Intentionally not fetched or baked while Festra serves public static tiles.",
    period: "current",
    licenceVerdict: "non-commercial-or-restricted",
  }
] as const satisfies SourceRecord[];

export type SourceRegistryId = (typeof SOURCE_REGISTRY)[number]["id"];

export function registryId<const T extends SourceRegistryId>(id: T): T {
  return id;
}

export const REGISTRY_BY_ID = new Map<string, SourceRecord>(
  SOURCE_REGISTRY.map((source) => [source.id, source])
);

export function assertBakeable(id: string): void {
  const source = REGISTRY_BY_ID.get(id);
  if (!source) {
    throw new Error(`Unknown source id ${id}`);
  }
  if (!source.licenceVerdict || !BAKEABLE_VERDICTS.has(source.licenceVerdict)) {
    throw new Error(
      `Source id ${id} is not bakeable: ${source.licenceVerdict ?? "missing licence verdict"}`
    );
  }
}
