/** sourceId -> raw/generated/public file fingerprinted by hash-sources. */
export type SourceFileMapping = {
  dir: "raw" | "generated" | "public";
  file: string;
};

export const SOURCE_FILES: Record<string, SourceFileMapping> = {
  "abs-sa2-income-dbr": { dir: "raw", file: "abs-sa2-income.json" },
  "abs-census-rent-2021": { dir: "raw", file: "abs-sa2-rent.json" },
  "abs-erp-sa2": { dir: "raw", file: "abs-sa2-erp.json" },
  "abs-erp-sa2-series": { dir: "raw", file: "abs-sa2-erp-series.json" },
  "vcsa-recorded-offences": { dir: "raw", file: "vcsa-lga-offences.xlsx" },
  "act-policing-crime-statistics": { dir: "raw", file: "act-crime-statistics.xlsx" },
  "qps-lga-offence-rates": { dir: "raw", file: "qld-lga-offence-rates.csv" },
  "bocsar-suburb-offences": { dir: "raw", file: "nsw-bocsar-suburb-offences.csv" },
  "wa-police-suburb-offences": { dir: "raw", file: "wa-police-suburb-offences.csv" },
  "sapol-suburb-offences": { dir: "raw", file: "sa-sapol-suburb-offences.csv" },
  "ptv-gtfs": { dir: "generated", file: "gtfs-transport.json" },
  "osm-pt": { dir: "raw", file: "osm-pt.json" },
  "vic-mapshare-hospitals": { dir: "raw", file: "vic-hospitals.json" },
  "vicmap-police": { dir: "raw", file: "vic-police.json" },
  "vicmap-foi": { dir: "raw", file: "vic-childcare.json" },
  "osm-health": { dir: "raw", file: "osm-health.json" },
  "osm-post": { dir: "raw", file: "osm-post.json" },
  "osm-clinical-social": { dir: "raw", file: "osm-clinical-social.json" },
  "abs-census-labour-2016": { dir: "raw", file: "abs-sa2-employment.json" },
  "abs-census-preschool-2021": { dir: "raw", file: "abs-sa2-employment.json" },
  "vic-planning-bpa": { dir: "raw", file: "vic-bpa.geojson" },
  "vic-planning-flood": { dir: "raw", file: "vic-lsio.geojson" },
  "qld-spp-bushfire-prone-area": { dir: "raw", file: "qld-bpa.geojson" },
  "bcc-cityplan-flood-overlay": { dir: "raw", file: "qld-bcc-flood.geojson" },
  "nsw-rfs-bush-fire-prone-land": { dir: "raw", file: "nsw-bfpl.geojson" },
  "nsw-epi-flood-planning-area": { dir: "raw", file: "nsw-epi-flood.geojson" },
  "wa-dfes-bushfire-prone-areas-2025": { dir: "raw", file: "wa-bpa.geojson" },
  "sa-plansa-bushfire-hazards": { dir: "raw", file: "sa-plansa-bushfire.geojson" },
  "sa-plansa-flood-hazards": { dir: "raw", file: "sa-plansa-flood.geojson" },
  "nsw-beachwatch": { dir: "public", file: "beach-quality.sydney.json" },
  "vic-planning-heritage": { dir: "raw", file: "vic-ho.geojson" },
  "vic-planning-overlays": { dir: "raw", file: "vic-conservation-overlays.geojson" },
  "vic-coastal-inundation": { dir: "raw", file: "vic-sea-level.geojson" },
  "vic-fire-history": { dir: "raw", file: "vic-fire-history.geojson" },
  "vif2023-sa2": { dir: "raw", file: "vif2023-sa2.xlsx" },
  "abs-building-approvals": { dir: "raw", file: "abs-sa2-approvals.json" },
  "vic-school-zones": { dir: "public", file: "school-zones.json" },
  "dtp-aadt": { dir: "public", file: "traffic-aadt.json" },
  "vic-water-corp": { dir: "raw", file: "water-corp.geojson" },
  "epa-air": { dir: "public", file: "epa-air-sites.json" },
  "abs-census-tsp-sa2": { dir: "raw", file: "abs-sa2-affordability.json" },
  "vic-activity-centres": { dir: "public", file: "activity-centres.json" },
  "osm-noise-corridors": { dir: "public", file: "noise-lines.json" },
  "osm-nuisance-points": { dir: "public", file: "nuisance-points.json" },
  "osm-train-stations": { dir: "public", file: "train-stations.json" },
  "osm-schools": { dir: "raw", file: "osm-schools.json" },
  "osm-amenities": { dir: "raw", file: "osm-amenities.json" },
  "osm-cycleways": { dir: "raw", file: "osm-cycleways.json" },
  "osm-aged-care": { dir: "raw", file: "osm-aged-care.json" },
  "abs-seifa-2021": { dir: "raw", file: "abs-sa2-seifa.json" },
  "abs-census-community-2021": { dir: "raw", file: "abs-sa2-community.json" },
  "abs-census-g49-sa2": { dir: "raw", file: "abs-sa2-qualifications.json" },
  "osm-future-transport": { dir: "public", file: "future-transport.json" },
  "vic-doe-school-locations": { dir: "raw", file: "vic-schools-by-sa2.json" },
};
